dist: trusty
sudo: required
language: c
compiler:
  - gcc

before_install:
  - git clone git://git.cryptomilk.org/projects/cmocka.git 
  - cd cmocka
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ..
  - cd ../../

  - git clone https://github.com/gonapps-org/libgenc
  - cd libgenc
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ..
  - cd ../../

install:
  - cd cmocka/build
  - make
  - sudo make install
  - cd ../../

  - cd libgenc/build
  - make
  - sudo make install
  - cd ../../

before_script:
  - cmake -version
  - make --version 
  - gcc --version
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ..

script: make && ctest --verbose
